default:
    - override hydra/output: local
    - override hydra/launcher: local

data:
  logs_folder: '/home/gaoyuez/dataset-tst/'
  pickle_fn: '12-07-lift-box.pkl'
  subsample_period: 1
  in_dim: 7
  out_dim: 7
  tracking: null
  images:
    cameras: []
    im_h: 480
    im_w: 640
    per_img_out: 128
  relabel:
    window: 0
    src: "jointstate"
  noise: 0.0

agent:
  type: 'bc'
  description: NA

training:
  lr: 1e-3
  seed: 0
  epochs: 80
  device: 'cuda:0'
  batch_size: 128
  save_every_x_epoch: 10

debug: False
