default:
    - override hydra/output: local
    - override hydra/launcher: local

data:
  pickle_fn: '12-07-lift-box.pkl'
  in_dim: 8
  out_dim: 8
  tracking:
    marker_ids:
      - 5
    tracking_cameras:
      - 'cam1c'
      - 'cam2c'
  images:
    cameras: []
    im_h: 480
    im_w: 640
    per_img_out: 128
  relabel:
    window: 32
    src: "tracking"
  noise: 0.0

agent:
  type: 'bc'
  description: NA

training:
  lr: 1e-3
  seed: 0
  epochs: 80
  device: 'cuda:0'
  batch_size: 128
  save_every_x_epoch: 10

debug: False
