default:
    - override hydra/output: local
    - override hydra/launcher: local

data:
  logs_folder: '/home/gaoyue/Desktop/cloud-dataset-inserting-v0'
  pickle_fn: '/home/gaoyue/Desktop/cloud-dataset-inserting-v0/parsed_with_embeddings_moco_conv3.pkl'
  subsample_period: 1
  in_dim: 7
  out_dim: 7
  tracking: null
  images:
    cameras: # A list of camera images to use, or [] to not use cameras
      - 'cam0c'
    im_h: 480
    im_w: 640
    per_img_out: 128
  relabel:
    window: 0
    src: "jointstate"
  noise: 0.0

agent:
  type: 'bcimage'
  fix_resnet: True
  custom_resnet_path: 'moco_conv3'
  description: ""
  name: ''

training:
  lr: 1e-4
  seed: 0
  epochs: 80
  device: 'cuda:0'
  batch_size: 16
  save_every_x_epoch: 10

debug: False