default:
    - override hydra/output: local
    - override hydra/launcher: local

data:
  logs_folder: '/home/gaoyue/Desktop/cloud-dataset-inserting-v0'#'/home/gaoyuez/dataset-tst/'
  pickle_fn: '/home/gaoyue/Desktop/cloud-dataset-inserting-v0/parsed_with_depth.pkl'
  subsample_period: 1
  in_dim: 7
  out_dim: 7
  tracking: null
  images:
    cameras: # A list of camera images to use, or [] to not use cameras
      - 'cam0c'
    im_h: 120
    im_w: 160
    per_img_out: 256
  relabel:
    window: 0
    src: "jointstate"
  noise: 0.0

agent:
  type: 'bcimage'
  vision_model: 'rb2'
  vision_model_path: '/home/gaoyue/dev/franka_learning/outputs/rb2/insertion_pretrained_features99.pt'#'/home/gaoyue/data/suraj/snapshot_980000.pt'
  fix_resnet: True
  description: ""
  name: ''

training:
  lr: 1e-4
  seed: 0
  epochs: 40
  device: 'cuda:0'
  batch_size: 8
  save_every_x_epoch: 10

debug: False