default:
    - override hydra/output: local
    - override hydra/launcher: local

data:
  pickle_fn: '11-18-reach-tags.pkl'
  in_dim: 8
  out_dim: 8
  tracking: null
  images:
    cameras: # A list of camera images to use, or [] to not use cameras
      - 'cam0c'
    im_h: 480
    im_w: 640
    per_img_out: 128
  relabel:
    window: 32
    src: "cam0c"
  noise: 0.0

agent:
  type: 'bcimagegoal'
  vision_model: 'resnet'
  vision_model_path: '/private/home/aok/data/suraj/snapshot_980000.pt'
  fix_resnet: True
  description: ""
  name: ''

training:
  lr: 1e-3
  seed: 0
  epochs: 80
  device: 'cuda:0'
  batch_size: 128
  save_every_x_epoch: 10

debug: False